before_script:
  - ln -s /builds /go/src/$(echo "github.com/jcarley/harbor" | cut -d "/" -f1)
  - cd /go/src/github.com/jcarley/harbor
  - mkdir -p public/assets
  - go get -u github.com/gobuffalo/buffalo/buffalo
  - go get -t -v ./...
  - export PATH="$PATH:$GOPATH/bin"

stages:
  - test

.test-vars: &test-vars
  variables:
    GO_ENV: "test"
    POSTGRES_DB: "harbor_test"
    TEST_DATABASE_URL: "postgres://postgres:postgres@postgres:5432/harbor_test?sslmode=disable"

# Golang version choice helper
.use-golang-image: &use-golang-latest
  image: golang:latest

.use-golang-image: &use-golang-1-8
  image: golang:1.8

test:latest:
  <<: *use-golang-latest
  <<: *test-vars
  stage: test
  services:
    - postgres:latest
  script:
    - buffalo test

test:1.8:
  <<: *use-golang-1-8
  <<: *test-vars
  stage: test
  services:
    - postgres:latest
  script:
    - buffalo test
